name: Run Traffic Binary on Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts

      - name: Upload binary to remote server
        run: |
          scp -i ~/.ssh/id_rsa bgmi almalinux@${{ secrets.REMOTE_SERVER }}:/home/almalinux/

      - name: Run binary on remote server
        run: |
          ssh -i ~/.ssh/id_rsa almalinux@${{ secrets.REMOTE_SERVER }} "chmod +x /home/almalinux/bgmi && /home/almalinux/bgmi"
