name: Run Traffic Binary on Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send_traffic:
    runs-on: ubuntu-latest

    steps:
      # Step to set up the SSH key for authentication
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Replace this with the actual server IP address stored in secrets
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts

      # Step to upload the binary file (bgmi) to the remote server
      - name: Upload binary to remote server
        run: |
          # Ensure bgmi is executable
          chmod +x bgmi
          # Upload the file using scp
          scp -i ~/.ssh/id_rsa bgmi almalinux@${{ secrets.REMOTE_SERVER }}:/home/almalinux/

      # Step to run the binary file on the remote server
      - name: Run binary on remote server
        run: |
          # SSH into the remote server and run bgmi
          ssh -i ~/.ssh/id_rsa almalinux@${{ secrets.REMOTE_SERVER }} "chmod +x /home/almalinux/bgmi && /home/almalinux/bgmi"
